### ISSUE TITLE
Bug report: Text is no longer correct for setup

### ISSUE THREAD

**Issue by funkymonkeymonk** [funkymonkeymonk/MarvelChampionsScripted#20]
The text in the beginning (Hero -> Villain -> Modular) is no longer correct, since you also need to select the Difficulty (i.e. Hero -> Villain -> Difficulty -> Modular would be better as a reminder).

**Comment by SwedeRacer** [comment]
I'm not sure what this is referring to. I don't see this text anywhere on the table or in the code.

**Comment by SwedeRacer** [comment]
I figured out that this is referring to the message that is displayed when you select the number of players. I adjusted it.
