### ISSUE TITLE
Bug: Encounter deck name changes based on what is added

### ISSUE THREAD

**Issue by funkymonkeymonk** [funkymonkeymonk/MarvelChampionsScripted#21]
I loaded the game, set for one player, selected hero and villain, and then a modular set. The whole encounter deck was then "named" after the modular set. Seems to be specific to the Zzzax Modular Encounter Set. It worked fine with Masters of Evil.

**Comment by SwedeRacer** [comment]
I couldn't reproduce this issue, but I think it may have been fixed by my recent changes to the modular sets. I now set each set's name to a blank string as it's being placed on the deck, so that probably solved the issue.
