### ISSUE TITLE
Bug: Ironheart name only on stage 2 and 3, not in stage 1

### ISSUE THREAD

**Issue by funkymonkeymonk** [funkymonkeymonk/MarvelChampionsScripted#27]
Ironheart identity card (hero side) is only called Ironheart on State 2 and 3 (but not 1).

**Comment by SwedeRacer** [comment]
The HeroPlacer clears the name of identity cards as it places them (the seem unnecessary, and the hover text is distracting), but that only affects the current state of the card, so for Ironheart, I had to manually clear the names of the other two identities, to make them all consistent.
